<a href="https://colab.research.google.com/github/Sanaz-salari/Deep-Learning/blob/main/Problem_Single_layer_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Two_Class_Gaussian_Data.csv to Two_Class_Gaussian_Data.csv

In [ ]:
uploaded

{'Two_Class_Gaussian_Data.csv': b'x1,x2,y\r\n-0.2418,-0.8484,1\r\n-1.6919,1.0404,1\r\n-0.3198,0.6226,1\r\n-2.0725,-0.7876,1\r\n-0.1002,0.4883,1\r\n-3.1231,-0.0767,1\r\n-0.7153,-1.7514,1\r\n-1.7333,-0.1454,1\r\n-1.7734,-0.6569,1\r\n-0.8482,-0.0682,1\r\n-1.3368,-0.261,1\r\n-0.0292,-2.8278,1\r\n-1.1072,-3.5697,1\r\n0.0135,-1.0386,1\r\n-1.4753,-1.6361,1\r\n-0.9311,-0.2481,1\r\n-0.6014,0.171,1\r\n0.1163,-2.4061,1\r\n-0.3795,-0.4374,1\r\n-1.2877,-0.7189,1\r\n-2.3718,-0.8224,1\r\n-1.6859,0.7061,1\r\n-0.6683,-1.6133,1\r\n-1.9977,0.5622,1\r\n-0.7086,0.226,1\r\n0.1071,-3.3626,1\r\n-0.755,1.4319,1\r\n-0.835,0.092,1\r\n-0.5938,-0.2937,1\r\n0.216,-2.2724,1\r\n0.4484,-1.9473,1\r\n-2.0251,-1.6755,1\r\n-0.7946,-2.2005,1\r\n-0.4111,-2.0695,1\r\n-1.264,-0.3578,1\r\n1.4953,-0.6519,1\r\n-0.1441,-0.2606,1\r\n-1.851,-1,1\r\n-0.1881,-3.2918,1\r\n-0.2998,-1.1449,1\r\n-0.2401,-2.0169,1\r\n-2.7129,-1.6846,1\r\n0.537,-1.3805,1\r\n-2.6098,0.3083,1\r\n0.1095,-0.8129,1\r\n-2.1097,-0.6757,1\r\n-0.6145,-1.5543,1\r\n-0.0348,-1.6608,1\r\n-0.1817,-1.5601,1\r\n-0.963,-0.8301,1\r\n-1.926,0.9216,1\r\n-1.1119,-0.8405,1\r\n-1.803,-0.035,1\r\n-2.665,1.6339,1\r\n-1.9014,-0.8431,1\r\n-0.4117,-0.6619,1\r\n-0.4458,-1.0225,1\r\n-1.4152,-1.5278,1\r\n-0.9382,-3.2253,1\r\n-0.5426,-3.2889,1\r\n-0.801,-1.3994,1\r\n-0.7424,-1.6579,1\r\n1.0807,-2.3939,1\r\n-3.2772,-1.0873,1\r\n-0.661,-0.9728,1\r\n-0.7101,-0.9648,1\r\n-0.3377,-1.9544,1\r\n-1.5809,-0.0533,1\r\n-0.1122,-2.8669,1\r\n-0.8281,-2.0012,1\r\n-0.1512,-1.6424,1\r\n-0.0362,-2.6064,1\r\n0.3219,-0.5929,1\r\n-1.0643,0.3266,1\r\n0.3171,-1.4542,1\r\n-0.772,-2.3302,1\r\n-2.4296,0.2853,1\r\n-1.1497,-3.1392,1\r\n-1.505,-1.2108,1\r\n-2.7291,2.638,1\r\n-1.4175,-0.4109,1\r\n-1.615,-1.6884,1\r\n-0.2792,-0.5924,1\r\n-0.6606,-1.4151,1\r\n-0.1172,-0.5448,1\r\n-0.7158,-1.4581,1\r\n-1.1455,0.235,1\r\n-1.0896,-0.0815,1\r\n-0.7108,-0.9594,1\r\n0.1648,-1.8416,1\r\n-0.1943,-1.1813,1\r\n-2.3556,-0.4874,1\r\n-0.8791,-1.1289,1\r\n-1.2222,-0.2828,1\r\n-0.4283,-1.9757,1\r\n-1.3001,-1.5439,1\r\n0.1343,-1.5737,1\r\n-1.1794,-1.5398,1\r\n-2.4671,-1.5576,1\r\n0.3953,-0.9439,1\r\n-0.5592,-1.4505,1\r\n-0.4346,-2.6395,1\r\n-1.6936,-0.995,1\r\n-0.1661,-1.5415,1\r\n-3.2374,-1.9028,1\r\n0.0976,-2.7245,1\r\n-1.0016,-2.5716,1\r\n-2.6146,0.7672,1\r\n-2.2287,-0.5087,1\r\n-0.7926,-0.14,1\r\n-0.7791,-0.6261,1\r\n-2.0061,-0.0827,1\r\n-1.4531,-1.3618,1\r\n0.3995,-1.4529,1\r\n-1.462,-1.9234,1\r\n-0.9673,-1.6433,1\r\n-0.2012,-1.9741,1\r\n-0.1032,-1.2766,1\r\n-0.8621,-2.6233,1\r\n-2.6191,-1.3922,1\r\n-2.6466,-0.0054,1\r\n-0.5713,0.0581,1\r\n-1.7372,-0.314,1\r\n-0.4351,-1.6659,1\r\n-2.3842,-0.35,1\r\n-0.5397,-1.1628,1\r\n-0.3706,0.3809,1\r\n-0.6202,-1.253,1\r\n-2.0133,0.3197,1\r\n-1.3472,-0.8953,1\r\n-0.5581,-1.9146,1\r\n-2.5902,0.0631,1\r\n-1.7014,0.2616,1\r\n-2.0776,-1.9024,1\r\n0.0022,-2.4458,1\r\n0.7295,-2.0308,1\r\n-0.291,-0.9532,1\r\n-1.7479,-1.4264,1\r\n-0.7711,-1.6771,1\r\n-1.2235,-0.3488,1\r\n-1.8533,-1.7296,1\r\n-0.6544,-0.2655,1\r\n-0.8902,-0.3072,1\r\n-2.133,-0.9898,1\r\n-1.6831,-0.0869,1\r\n-1.2779,0.2597,1\r\n-0.3452,-1.055,1\r\n-2.2484,0.3686,1\r\n-1.5975,-0.5898,1\r\n-1.4818,-0.7447,1\r\n-0.0166,-1.5547,1\r\n0.7621,-2.7422,1\r\n0.4274,-2.3609,1\r\n-0.0882,-1.4826,1\r\n-0.6732,-0.3075,1\r\n-0.9304,-1.5536,1\r\n-2.4998,1.0287,1\r\n-1.4182,-1.4957,1\r\n-1.021,-0.4309,1\r\n-0.7716,-2.2486,1\r\n-2.0082,-1.2471,1\r\n-1.6646,-1.0784,1\r\n-0.4418,-1.0865,1\r\n-2.1885,1.2149,1\r\n-1.7755,-0.517,1\r\n-0.729,-1.4918,1\r\n0.535,-1.3247,1\r\n-2.0523,-1.5123,1\r\n-0.3744,-1.3962,1\r\n-1.7976,-0.2151,1\r\n-1.3135,-1.0994,1\r\n-1.6022,-0.8444,1\r\n0.2591,-1.474,1\r\n-0.1415,-1.0645,1\r\n-3.1053,1.5056,1\r\n-1.3609,0.9099,1\r\n-0.4464,-0.6732,1\r\n-2.5564,-1.4051,1\r\n-1.2067,-0.5823,1\r\n-1.4256,-1.2783,1\r\n-0.5062,-2.1512,1\r\n-1.8709,0.0392,1\r\n-0.9202,-0.6207,1\r\n-1.5216,-0.907,1\r\n-2.4139,-0.6205,1\r\n-1.3843,-1.5755,1\r\n-1.4579,-2.3647,1\r\n-1.2915,-2.2643,1\r\n-1.3012,-1.8659,1\r\n-2.5886,-0.5655,1\r\n0.0943,-1.3955,1\r\n0.3242,-1.4634,1\r\n-1.1265,-2.0114,1\r\n-1.7372,-0.0252,1\r\n-0.7863,-0.7372,1\r\n-1.4005,0.4602,1\r\n-0.9351,-1.4743,1\r\n-2.758,-0.1268,1\r\n0.6867,-2.2985,1\r\n-0.6726,-0.5422,1\r\n-0.284,-0.4154,1\r\n0.5986,-1.3658,1\r\n-3.0647,2.4328,1\r\n-1.7436,-0.767,1\r\n-0.8238,-0.7161,1\r\n-0.4722,-2.9672,1\r\n-1.5532,-1.1963,1\r\n-0.7017,-2.7845,1\r\n-2.2266,-0.4802,1\r\n-1.1897,-2.045,1\r\n-1.3017,-1.4317,1\r\n-0.043,-2.2599,1\r\n-1.5334,-0.8674,1\r\n-1.9011,0.2709,1\r\n-1.8926,0.7889,1\r\n-0.7213,-0.7678,1\r\n-1.7458,-1.1128,1\r\n0.6035,-1.6464,1\r\n-0.4257,-1.9553,1\r\n-0.6793,-1.9773,1\r\n-1.1514,-2.1433,1\r\n-0.6842,-2.8086,1\r\n0.3437,-1.7284,1\r\n-3.2378,0.701,1\r\n0.2929,-1.4679,1\r\n-1.3785,-0.8178,1\r\n-0.9975,-0.9839,1\r\n-0.1154,-1.9259,1\r\n-0.4175,0.3422,1\r\n-2.6142,-0.3834,1\r\n-2.5037,-1.4731,1\r\n-0.4264,-1.549,1\r\n-1.9105,-1.038,1\r\n-2.6313,-0.2896,1\r\n-1.3591,-1.1583,1\r\n-1.3976,-1.5324,1\r\n-2.1613,-1.9243,1\r\n-2.1098,-0.8344,1\r\n-0.7093,-2.4859,1\r\n-2.9102,-0.1278,1\r\n0.3148,-0.8713,1\r\n-0.3347,0.7195,1\r\n-1.2751,-0.4123,1\r\n-1.023,-0.633,1\r\n-1.908,0.3656,1\r\n-2.0437,-0.1068,1\r\n-0.6265,-0.0652,1\r\n-0.0985,-1.6119,1\r\n0.2785,-1.5261,1\r\n-1.1285,-1.5053,1\r\n0.2407,1.6921,0\r\n0.4048,1.228,0\r\n1.8124,1.2427,0\r\n1.0695,-0.5867,0\r\n-0.8337,2.9675,0\r\n2.8274,0.0339,0\r\n1.6541,0.333,0\r\n-0.5448,2.3003,0\r\n0.6249,1.7449,0\r\n1.2077,1.7791,0\r\n0.2344,2.1921,0\r\n0.8936,2.1172,0\r\n1.3388,0.6146,0\r\n2.0335,-0.1295,0\r\n-0.4048,1.1881,0\r\n-0.0306,1.2881,0\r\n0.3566,2.398,0\r\n1.1708,-0.4268,0\r\n2.3448,-0.0074,0\r\n2.9363,0.2701,0\r\n1.7413,1.3448,0\r\n1.812,-0.2541,0\r\n0.8572,0.9811,0\r\n0.9001,1.1606,0\r\n0.1999,1.4542,0\r\n1.4932,1.0752,0\r\n2.2376,0.2912,0\r\n2.296,-0.2514,0\r\n0.7218,0.8041,0\r\n1.2171,0.9054,0\r\n1.6307,1.8704,0\r\n0.4515,1.6353,0\r\n1.2296,0.9447,0\r\n1.3553,1.0771,0\r\n1.5213,1.1487,0\r\n0.384,2.8519,0\r\n2.3458,0.5528,0\r\n1.9749,1.8209,0\r\n-1.3779,2.4635,0\r\n-0.0923,2.242,0\r\n0.6743,1.6659,0\r\n-1.0122,3.5464,0\r\n2.5677,-0.5962,0\r\n1.2333,0.0895,0\r\n1.6464,1.0024,0\r\n-0.1294,2.3526,0\r\n1.197,1.0351,0\r\n2.6969,-0.0236,0\r\n1.726,1.9262,0\r\n1.7925,0.0654,0\r\n1.6034,1.3994,0\r\n0.9416,2.6996,0\r\n-0.1087,1.8973,0\r\n3.1442,-0.8181,0\r\n-0.3528,3.7825,0\r\n1.457,0.0436,0\r\n1.3912,1.0473,0\r\n3.073,0.674,0\r\n0.6767,2.225,0\r\n2.4681,0.2109,0\r\n0.4976,1.81,0\r\n1.2096,-0.6388,0\r\n1.7548,0.6742,0\r\n0.0518,0.8158,0\r\n1.6132,-0.7709,0\r\n2.7605,1.0756,0\r\n1.0888,2.2222,0\r\n3.5956,-0.0932,0\r\n0.3245,0.3871,0\r\n3.7868,1.6983,0\r\n0.9832,0.6602,0\r\n1.2717,1.6558,0\r\n0.0859,1.3393,0\r\n-0.9514,3.1138,0\r\n0.6826,1.4379,0\r\n1.5883,0.2932,0\r\n1.829,0.6515,0\r\n-0.6749,1.7464,0\r\n-0.9223,3.1883,0\r\n0.5633,1.8314,0\r\n1.045,1.2961,0\r\n3.4166,-0.7304,0\r\n0.6901,0.417,0\r\n1.1876,1.4736,0\r\n1.9477,1.7994,0\r\n0.4743,0.561,0\r\n-0.1156,0.4526,0\r\n-0.5923,3.2877,0\r\n2.1748,0.5008,0\r\n1.4851,0.0629,0\r\n2.6455,-0.906,0\r\n0.5458,2.299,0\r\n2.0088,1.819,0\r\n3.0494,1.5142,0\r\n1.602,1.2456,0\r\n1.0179,1.0632,0\r\n-0.6104,3.6585,0\r\n2.2388,1.4748,0\r\n1.6836,-0.8579,0\r\n0.2193,1.3779,0\r\n1.531,2.8719,0\r\n3.1345,-0.6468,0\r\n1.3544,1.0479,0\r\n1.2317,0.5617,0\r\n2.288,1.4979,0\r\n0.9865,0.4412,0\r\n-0.3333,1.7205,0\r\n0.4437,0.6409,0\r\n1.7556,0.4669,0\r\n0.0881,2.3953,0\r\n2.3717,0.4327,0\r\n1.2456,0.8637,0\r\n1.1188,0.1278,0\r\n1.3847,-0.4724,0\r\n0.9298,1.3485,0\r\n0.4217,1.7029,0\r\n1.4693,1.044,0\r\n2.2997,-1.2759,0\r\n2.6348,0.772,0\r\n0.2972,1.5535,0\r\n1.8073,1.6698,0\r\n-0.0275,1.6226,0\r\n2.2945,0.5084,0\r\n1.0149,0.4685,0\r\n1.2187,-0.0073,0\r\n2.7132,-0.1123,0\r\n-1.0788,3.3004,0\r\n1.1129,2.5046,0\r\n-0.0865,0.3883,0\r\n-0.5583,2.1145,0\r\n1.6374,0.6615,0\r\n0.5954,1.2981,0\r\n0.5967,1.9056,0\r\n1.0841,0.0841,0\r\n0.5647,0.3477,0\r\n0.4374,1.5264,0\r\n1.8781,0.8119,0\r\n0.1854,1.1932,0\r\n0.7416,0.9396,0\r\n1.4933,1.5316,0\r\n0.1973,0.8452,0\r\n0.9917,0.8479,0\r\n1.6276,1.3079,0\r\n1.1544,1.1838,0\r\n3.5807,1.051,0\r\n-0.3062,1.6148,0\r\n2.0235,0.4626,0\r\n1.7778,0.2802,0\r\n0.1661,0.9372,0\r\n0.4133,2.1008,0\r\n1.0657,-0.1724,0\r\n0.9877,0.745,0\r\n0.923,-1.2128,0\r\n-0.5586,2.4549,0\r\n2.7026,0.6709,0\r\n0.531,2.051,0\r\n1.0946,0.066,0\r\n1.2871,0.7977,0\r\n1.9194,0.6111,0\r\n1.5101,-0.7854,0\r\n1.2454,-0.6653,0\r\n-0.4005,1.1284,0\r\n1.9696,1.6856,0\r\n2.5937,2.0533,0\r\n-0.4379,1.8634,0\r\n-0.5342,0.2903,0\r\n0.9253,1.2768,0\r\n1.0815,1.3009,0\r\n0.1568,1.3363,0\r\n0.4354,1.4351,0\r\n0.9718,-0.5775,0\r\n-0.2437,0.3208,0\r\n1.733,1.3429,0\r\n1.0596,0.7671,0\r\n1.1491,-0.4876,0\r\n2.5959,-0.0733,0\r\n0.2227,0.699,0\r\n2.5503,0.8231,0\r\n2.055,0.4361,0\r\n0.8333,1.364,0\r\n1.3145,1.2814,0\r\n2.4196,-0.6006,0\r\n1.3273,0.9224,0\r\n1.4757,0.6614,0\r\n1.3988,1.3975,0\r\n0.9272,2.6674,0\r\n2.3148,0.6244,0\r\n1.9783,0.4284,0\r\n2.7221,0.1659,0\r\n0.5877,0.6746,0\r\n1.5651,-0.7819,0\r\n1.7399,1.0447,0\r\n1.2201,0.5021,0\r\n2.3128,0.6786,0\r\n1.6292,0.7313,0\r\n-0.108,1.133,0\r\n0.553,1.4352,0\r\n0.274,1.9851,0\r\n1.354,0.9559,0\r\n0.4932,1.3692,0\r\n-1.1037,1.1805,0\r\n0.3353,2.4638,0\r\n2.4501,1.3134,0\r\n0.6702,-1.0671,0\r\n3.7019,-2.1577,0\r\n-0.6349,2.1519,0\r\n0.4637,0.5225,0\r\n1.5472,-0.3395,0\r\n2.4926,2.5414,0\r\n0.5448,0.4444,0\r\n0.5036,0.1888,0\r\n2.2353,0.645,0\r\n1.0409,0.3473,0\r\n1.7485,-0.3646,0\r\n2.2308,-0.8392,0\r\n1.3049,0.335,0\r\n2.0778,0.9105,0\r\n1.7652,-0.6754,0\r\n-0.3196,1.5847,0\r\n0.4908,1.2437,0\r\n1.5551,0.4229,0\r\n-0.9576,2.833,0\r\n0.2395,1.9373,0\r\n-1.4439,4.7507,0\r\n0.3406,0.2484,0\r\n0.8852,1.1935,0\r\n1.3001,1.533,0\r\n0.416,0.7922,0\r\n-2.0737,2.9938,0\r\n2.551,1.6722,0\r\n0.5926,1.8966,0\r\n2.4281,1.0513,0\r\n-0.3532,1.4825,0\r\n1.904,0.8052,0\r\n1.5417,0.278,0\r\n0.535,1.098,0\r\n3.4304,-0.3005,0\r\n3.0205,0.8533,0\r\n1.7973,0.9776,0\r\n1.031,0.9622,0\r\n1.5407,0.4006,0\r\n1.6839,0.4481,0\r\n0.4099,0.286,0\r\n0.7389,1.7858,0\r\n2.5171,1.2497,0\r\n2.0073,-0.39,0\r\n1.3034,2.3219,0\r\n0.1829,0.9806,0\r\n0.5088,1.3952,0\r\n1.8675,0.8729,0\r\n'}

In [ ]:
import pandas as pd
import io
  
df = pd.read_csv(io.BytesIO(uploaded['Two_Class_Gaussian_Data.csv']))
print(df)

         x1      x2  y
0   -0.2418 -0.8484  1
1   -1.6919  1.0404  1
2   -0.3198  0.6226  1
3   -2.0725 -0.7876  1
4   -0.1002  0.4883  1
..      ...     ... ..
495  2.0073 -0.3900  0
496  1.3034  2.3219  0
497  0.1829  0.9806  0
498  0.5088  1.3952  0
499  1.8675  0.8729  0

[500 rows x 3 columns]

In [ ]:
df2 = df
# Remove all columns between column index 1 to 3
df.drop(df.iloc[:, m+1:n+m], inplace = True, axis = 1)

In [ ]:
data = {
    'A':['A1', 'A2', 'A3', 'A4', 'A5'], 
    'B':['B1', 'B2', 'B3', 'B4', 'B5'], 
    'C':['C1', 'C2', 'C3', 'C4', 'C5'], 
    'D':['D1', 'D2', 'D3', 'D4', 'D5'], 
    'E':['E1', 'E2', 'E3', 'E4', 'E5'] }
data = pd.DataFrame(data)
data

    A   B   C   D   E
0  A1  B1  C1  D1  E1
1  A2  B2  C2  D2  E2
2  A3  B3  C3  D3  E3
3  A4  B4  C4  D4  E4
4  A5  B5  C5  D5  E5

In [ ]:
data

    A   B   C   D   E
0  A1  B1  C1  D1  E1
1  A2  B2  C2  D2  E2
2  A3  B3  C3  D3  E3
3  A4  B4  C4  D4  E4
4  A5  B5  C5  D5  E5

In [ ]:
data2 = data.copy()

In [ ]:
data2 = data.copy()
m=2
n=3
i=1  #'D'
data2.drop(data2.iloc[:, m:m+i], inplace = True, axis = 1)
data2.drop(data2.iloc[:, m+1:], inplace = True, axis = 1)
#data2.drop(data2.iloc[:, 2:3], inplace = True, axis = 1)
data2

    A   B   D
0  A1  B1  D1
1  A2  B2  D2
2  A3  B3  D3
3  A4  B4  D4
4  A5  B5  D5

In [ ]:
i = 0
data2.drop(data2.iloc[:, m:m+i], inplace = True, axis = 1)
data2.drop(data2.iloc[:, m+1:], inplace = True, axis = 1)
data2

    A   B   D
0  A1  B1  D1
1  A2  B2  D2
2  A3  B3  D3
3  A4  B4  D4
4  A5  B5  D5

In [ ]:
len(range(0,1))

1

In [ ]:
df_save = df
shape = df.shape
N = shape[0] # no. of rows of 'df'

In [ ]:
# Select first m columns of dataframe (m is no of features)
m=2
df_x  = df.iloc[: , :m]  #datframe of x(features)
df_x.head()

       x1      x2
0 -0.2418 -0.8484
1 -1.6919  1.0404
2 -0.3198  0.6226
3 -2.0725 -0.7876
4 -0.1002  0.4883

In [ ]:
n=1 # no. of output (yi)
no_output_node  = df.iloc[: , -n:]
no_output_node.head()

   y
0  1
1  1
2  1
3  1
4  1

In [ ]:
df.iloc[1:2]

       x1      x2  y
1 -1.6919  1.0404  1

In [ ]:
import numpy as np
a=np.array([[1,4,2]])  #matrix: 1x3
b = np.array([[1,4,2],[9, 0, 8]]) #matrix: 2x3

In [ ]:


# Make a prediction with weights
# To check y for each row to know whether w0+w1*x1+w2*x2 for each row is greater than 0, so y for that row would be 1, otherwise 0.
def predict(row, weights):
	activation = weights[0] # This line shows the linear summation value in a neuron. The activation function has not been performed on it. When it enters the activation function, it returns 1 or 0.
	for i in range(len(row)-1):   
		activation += weights[i + 1] * row[i]
	return 1.0 if activation >= 0.0 else 0.0  # here it is step function activation and it returns y.

  
# Estimate Perceptron weights using stochastic gradient descent

# train: training dataset ---> [x11, x12, y1; x21, x22, y2; ... ; xn1, xn2, yn], a matrix with n*3 dimensions
# l_rate: learning rate ---> Used to limit the amount each weight is corrected each time it is updated.
# n_epoch:  The number of times to run through the training data while updating the weight.
def train_weights(train, l_rate, n_epoch):
	weights = [0.0 for i in range(len(train[0]))] # [0.0, 0.0, 0.0]
	for epoch in range(n_epoch):
		sum_error = 0.0

# To update bias each time a row is entered, although bias is not associated with a specific input data
		for row in train:
			prediction = predict(row, weights)
			error = row[-1] - prediction
			sum_error += error**2
			weights[0] = weights[0] + l_rate * error # bias is updated and not associated with a specific input data

# To update other weights
			for i in range(len(row)-1): # len(row)-1 is 2, because we need to update weights only for x1 and x2. i=0,1
				weights[i + 1] = weights[i + 1] + l_rate * error * row[i] # row[i] is : dataset[row][i] : i=0 is x1 and i=1 is x2
        # in the above line since it doesn't calculate w0, so each w(i+1) is calculated based on its initialized w(i+1) which was 0 
		print('>epoch=%d, lrate=%.3f, error=%.3f' % (epoch, l_rate, sum_error))
	return weights

dataset = [[2.7810836,2.550537003,3.5, 0],
	[1.465489372,2.362125076,2.5, 0],
		[3.396561688,4.400293529,0],
	[0,3,0]]
l_rate = 0.1 # learning rate is a positive constant less than 1
n_epoch = 5
weights = train_weights(dataset, l_rate, n_epoch)


# Perceptron Algorithm With Stochastic Gradient Descent
def perceptron(train, test, l_rate, n_epoch):
	predictions = list() #To generate an empty list
	weights = train_weights(train, l_rate, n_epoch) # first, recall train-weights function to update weights
	for row in test:
		prediction = predict(row, weights) # second, generate predictions
		predictions.append(prediction)
	return(predictions)

array([[0]])

In [ ]:
b=[[1,3,2], [3, 2, 0]]
for row in b:
  actual=row[-1]
  print(actual)

2
0

In [ ]:
#The second way of modelling a perceptron
def perceptron2(X, y, lr, epochs):
    
    # X --> Inputs.
    # y --> labels/target.
    # lr --> learning rate.
    # epochs --> Number of iterations.
    
    # m-> number of training examples
    # n-> number of features 
    m, n = X.shape
    
    # Initializing parapeters(theta) to zeros.
    # +1 in n+1 for the bias term.
    theta = np.zeros((n+1,1))
    
    # Empty list to store how many examples were 
    # misclassified at every iteration.
    n_miss_list = []
    
    # Training.
    for epoch in range(epochs):
        
        # variable to store #misclassified.
        n_miss = 0
        
        # looping for every example.
        for idx, x_i in enumerate(X):
            
            # Insering 1 for bias, X0 = 1.
            x_i = np.insert(x_i, 0, 1).reshape(-1,1)
            
            # Calculating prediction/hypothesis.
            y_hat = step_func(np.dot(x_i.T, theta))
            
            # Updating if the example is misclassified.
            if (np.squeeze(y_hat) - y[idx]) != 0:
                theta += lr*((y[idx] - y_hat)*x_i)
                
                # Incrementing by 1.
                n_miss += 1
        
        # Appending number of misclassified examples
        # at every iteration.
        n_miss_list.append(n_miss)
        
    return theta, n_miss_list

In [ ]:
# Select first m columns of dataframe (m is no of features)
df_x  = df.iloc[: , :m]  #datframe of x(features)
df_x.head()

In [ ]:
n=1 # no. of output (yi)
no_y  = df.iloc[: , -n:]
no_y.head()

In [ ]:
l_rate = 0.5 # learning rate is a positive constant less than 1
n_epoch = 20
def step_func(z):
    return 1 if (z > 0) else 0

In [ ]:
yy = no_y.to_numpy()
xx = df_x.to_numpy()

In [ ]:
perceptron2(xx, yy, l_rate, n_epoch)

In [ ]:
 #train is a transpose of matrix X in my notes (length of column of train is no. of samples which is length of a row in X )

In [ ]:
# Make a prediction with weights
def predict(row, weights):
	activation = weights[0] 
	for i in range(len(row)-1):   
		activation += weights[i + 1] * row[i]
	return 1.0 if activation >= 0.0 else 0.0  

  
# Estimate Perceptron weights
def train_weights(train, l_rate, n_epoch):
	weights = [0.0 for i in range(len(train[0]))] 
	for epoch in range(n_epoch):
		sum_error = 0.0

# To update bias 
		for row in train:
			prediction = predict(row, weights)
			error = row[-1] - prediction
			sum_error += error**2
			weights[0] = weights[0] + l_rate * error # bias is updated

# To update other weights
			for i in range(len(row)-1): 
				weights[i + 1] = weights[i + 1] + l_rate * error * row[i] 
		print('>epoch=%d, lrate=%.3f, error=%.3f' % (epoch, l_rate, sum_error))
	return weights


# Calculate accuracy percentage
def accuracy_metric(actual, predicted):
	correct = 0
	for i in range(len(actual)):
		if actual[i] == predicted[i]:
			correct += 1
	return correct / float(len(actual)) * 100.0


# Perceptron Algorithm
def perceptron(train, test, l_rate, n_epoch):
  predictions = list() #To generate an empty list
  weights = train_weights(train, l_rate, n_epoch) # first, recall train-weights function to update weights
  for row in test:
    prediction = predict(row, weights) # second, generate predictions
    #print(row[-1])
    predictions.append(prediction)
  return prediction